name: UniversalCommands
version: 1.0.0-SNAPSHOT
author: Jan
main: de.jan.universalcommands.UniversalCommands
commands:
  executeAll:
    description: Executes this command on all connected spigot servers